In [65]:
"""
Universidad del Valle de Guatemala
HT2 2
Mineria de datos
Roberto Rios, 20979
Javier Valle, 20159
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
from sklearn.cluster import KMeans
import sklearn.cluster as cluster
import scipy.cluster.hierarchy as sch

In [66]:
# Ejercicio 1

# Cargando el csv con pandas.
import pandas as pd

df = pd.read_csv("movies.csv", encoding='ISO-8859-1')

# Imprimendo todas las columnas.
print(df.columns)

Index(['id', 'budget', 'genres', 'homePage', 'productionCompany',
       'productionCompanyCountry', 'productionCountry', 'revenue', 'runtime',
       'video', 'director', 'actors', 'actorsPopularity', 'actorsCharacter',
       'originalTitle', 'title', 'originalLanguage', 'popularity',
       'releaseDate', 'voteAvg', 'voteCount', 'genresAmount',
       'productionCoAmount', 'productionCountriesAmount', 'actorsAmount',
       'castWomenAmount', 'castMenAmount'],
      dtype='object')


In [67]:
# ejercicio 2

In [ ]:
# Primera gráfica de codo.

# Creando un arreglo con los datos de las columnas a utilizar.
X = np.array(df[["voteAvg", "voteCount", "popularity", "budget", "revenue", "runtime"]])


# Ejercicio 3: Calcular el número adecuado de grupos a formar.

clusters = range(1, 101)
wcss = []

# Cálculo de la varianza dentro del cluster.
for k in clusters:
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Graficando la varianza dentro del cluster.
pl.plot(clusters, wcss)
pl.title('Gráfica de codo')
pl.xlabel('Número de clusters')
pl.ylabel('Varianza dentro del cluster')
pl.show()

# Segunda gráfica de codo.

# Creando un arreglo con los datos de las columnas a utilizar.
Y = np.array(df[["genresAmount","voteAvg", "voteCount", "genresAmount"]])

clusters = range(1, 101)
wcss = []

# Cálculo de la varianza dentro del cluster.
for k in clusters:
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(Y)
    wcss.append(kmeans.inertia_)

# Graficando la varianza dentro del cluster.
pl.plot(clusters, wcss)
pl.title('Gráfica 2 de codo')
pl.xlabel('Número de clusters')
pl.ylabel('Varianza dentro del cluster')
pl.show()

# Tercera gráfica de codo.

# Creando un arreglo con los datos de las columnas a utilizar.
Z = np.array(df[["productionCoAmount", "productionCountriesAmount", "actorsAmount", "castWomenAmount", "castMenAmount"]])

clusters = range(1, 101)
wcss = []

# Cálculo de la varianza dentro del cluster.
for k in clusters:
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(Y)
    wcss.append(kmeans.inertia_)

# Graficando la varianza dentro del cluster.
pl.plot(clusters, wcss)
pl.title('Gráfica 3 de codo')
pl.xlabel('Número de clusters')
pl.ylabel('Varianza dentro del cluster')
pl.show()

In [73]:
# Ejercicio 4: Usar los algoritmos k-medias y cluster jerárquico para agrupar los datos.

# Creando el modelo de k-medias. Cluster X.
kmeans = KMeans(n_clusters=5)
kmeans.fit(X)

# Calculando el centroide de cada cluster.
centroids = kmeans.cluster_centers_
print(centroids)

cluster1 = kmeans.predict(X)

# Graficando los clusters.
pl.scatter(X[cluster1 == 0, 0], X[cluster1 == 0, 1],s=100,c='red', label = "Cluster 1")
pl.scatter(X[cluster1 == 1, 0], X[cluster1 == 1, 1],s=100,c='blue', label = "Cluster 1")
pl.scatter(X[cluster1 == 2, 0], X[cluster1 == 2, 1],s=100,c='green', label = "Cluster 1")
pl.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=300, c="yellow",marker="*", label="Centroides")
pl.title("Grupo 1")
pl.xlabel("Cluster1.length")
pl.ylabel("Cluster1.width")
pl.legend()

# Creando el modelo de k-medias. Cluster Y.
kmeans = KMeans(n_clusters=5)
kmeans.fit(Y)

# Calculando el centroide de cada cluster.
centroids = kmeans.cluster_centers_
print(centroids)

cluster2 = kmeans.predict(Y)


# Graficando los clusters.
pl.scatter(Y[cluster2 == 0, 0], Y[cluster2 == 0, 1],s=100,c='red', label = "Cluster 2")
pl.scatter(Y[cluster2 == 1, 0], Y[cluster2 == 1, 1],s=100,c='blue', label = "Cluster 2")
pl.scatter(Y[cluster2 == 2, 0], Y[cluster2 == 2, 1],s=100,c='green', label = "Cluster 2")
pl.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=300, c="yellow",marker="*", label="Centroides")
pl.title("Clusters")
pl.xlabel("Cluster1.length")
pl.ylabel("Cluster1.width")
pl.legend()


# Aplicando el clustering jerárquico a nuestro dataset. Cluster X.
jer1 = sch.dendrogram(sch.linkage(X, method = 'ward'))

hc1 = cluster.AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
especieHC1 = hc1.fit_predict(X)

print(especieHC1)

pl.scatter(X[especieHC1 == 0, 0], X[especieHC1 == 0, 1],s=100,c='red', label = "Cluster 1")
pl.scatter(X[especieHC1 == 1, 0], X[especieHC1 == 1, 1],s=100,c='blue', label = "Cluster 1")
pl.scatter(X[especieHC1 == 2, 0], X[especieHC1 == 2, 1],s=100,c='green', label = "Cluster 1")
pl.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=300, c="yellow",marker="*", label="Centroides")
pl.title("Clusters")
pl.xlabel("Clusters.length")
pl.ylabel("Clusters.width")
pl.legend()


# Aplicando el clustering jerárquico a nuestro dataset. Cluster X.
jer2 = sch.dendrogram(sch.linkage(Y, method = 'ward'))

hc1 = cluster.AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
especieHC1 = hc1.fit_predict(Y)

print(especieHC1)

pl.scatter(Y[especieHC1 == 0, 0], Y[especieHC1 == 0, 1],s=100,c='red', label = "Cluster 2")
pl.scatter(Y[especieHC1 == 1, 0], Y[especieHC1 == 1, 1],s=100,c='blue', label = "Cluster 2")
pl.scatter(Y[especieHC1 == 2, 0], Y[especieHC1 == 2, 1],s=100,c='green', label = "Cluster 2")
pl.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=300, c="yellow",marker="*", label="Centroides")
pl.title("Clusters")
pl.xlabel("Clusters.length")
pl.ylabel("Clusters.width")
pl.legend()

C:\Users\sebas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[[6.84926471e+00 6.56860294e+03 1.34273637e+02 9.92072193e+07
  3.95556500e+08 1.16938725e+02]
 [6.43350959e+00 6.15566035e+02 4.09837646e+01 6.80425893e+06
  9.46190409e+06 9.69501968e+01]
 [6.59855293e+00 2.96241813e+03 6.83010282e+01 5.03292768e+07
  1.42989070e+08 1.12134806e+02]
 [7.17037037e+00 1.22143111e+04 1.80798504e+02 1.53720000e+08
  8.77747269e+08 1.30385185e+02]
 [7.60000000e+00 1.66215000e+04 9.82367333e+02 2.39416667e+08
  1.90062248e+09 1.44666667e+02]]


C:\Users\sebas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[[2.52250304e+00 6.35656170e+00 3.45887552e+02 2.52250304e+00]
 [2.94505495e+00 7.72747253e+00 1.79169231e+04 2.94505495e+00]
 [2.88110749e+00 6.91498371e+00 5.24716124e+03 2.88110749e+00]
 [2.74441088e+00 6.68888218e+00 2.14871480e+03 2.74441088e+00]
 [2.99585062e+00 7.40082988e+00 1.01920166e+04 2.99585062e+00]]
